apiRules:
  - include:
      hasAttribute:
        uid: VisualPinball.Unity.ApiAttribute
  - exclude:
      uidRegex: '^VisualPinball\.Unity\..*'
      type: Type
  - exclude:    
      uidRegex: ^System\.Object
      type: Type