name: Dependents
on:
  repository_dispatch:
    types: [ publish-complete ]

jobs:
  VisualPinball-Unity-Hdrp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
           path: VisualPinball.Engine
      - name: Checkout VisualPinball.Unity.Hdrp
        uses: actions/checkout@v2
        with:
           repository: VisualPinball/VisualPinball.Unity.Hdrp
           path: VisualPinball.Unity.Hdrp
           token: ${{ secrets.GH_PAT }}
      - name: Update dependent
        id: updateDependent
        uses: VisualPinball/update-dependent-action@v0.1.0
        with:
          source: VisualPinball.Engine
          dependent: VisualPinball.Unity.Hdrp
      - name: Commit 
        if: ${{ steps.updateDependent.outputs.isBump == 'true' }} 
        run: |
          cd VisualPinball.Unity.Hdrp
          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add package.json
          git commit -m "chore(deps): Update ${{ steps.updateDependent.outputs.sourceName }} to ${{ steps.updateDependent.outputs.sourceVersion }}."
          git push

  VisualPinball-Unity-Urp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
           path: VisualPinball.Engine
      - name: Checkout VisualPinball.Unity.Urp
        uses: actions/checkout@v2
        with:
           repository: VisualPinball/VisualPinball.Unity.Urp
           path: VisualPinball.Unity.Urp
           token: ${{ secrets.GH_PAT }}
      - name: Update dependent
        id: updateDependent
        uses: VisualPinball/update-dependent-action@v0.1.0
        with:
          source: VisualPinball.Engine
          dependent: VisualPinball.Unity.Urp
      - name: Commit
        if: ${{ steps.updateDependent.outputs.isBump == 'true' }}
        run: |
          cd VisualPinball.Unity.Urp
          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add package.json
          git commit -m "chore(deps): Update ${{ steps.updateDependent.outputs.sourceName }} to ${{ steps.updateDependent.outputs.sourceVersion }}."
          git push
